* Kevin Kelley's PPA Emacs in Docker
  This repository contains all the necessary tools to build a Docker image with Emacs installed from [[https://launchpad.net/~kelleyk/+archive/ubuntu/emacs][Kevin Kelley's Emacs PPA package]].

  The image is built (by default) from latest Ubuntu LTS version, adds kelleyk's Emacs PPA from Launchpad and installs Emacs using Ubuntu's standard ~apt-get~. You only need Docker installed on your system.

  You can specify both the Ubuntu version and Emacs package to install on build using [[https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg][build args]], with ~emacs28~ on Jammy as defaults, since ~emacs~ would install Ubuntu's package. See the PPA page for package details.

** Usage
*** Build
   By default, the image is based on Ubuntu Jammy and installs the ~emacs28~ package via ~apt-get~. Use the optional ~UBUNTU_VERSION~ and ~EMACS_PACKAGE~ build args to customize:
   #+begin_src shell
   # Build from local git repo, explicitly specifying Ubuntu Focal's 'emacs27' package.
   docker build --build-arg UBUNTU_VERSION=focal --build-arg EMACS_PACKAGE=emacs27 -t kelleyk-emacs .
   #+end_src
   The Docker image can be built directly from this repo (ie. without cloning locally) by passing its URL as argument:
   #+begin_src shell
   # Build directly from git repo, specifying the 'main' branch (by default 'master', if not specified).
   docker build -t kelleyk-emacs github.com/pataquets/docker-kelleyk-ppa-emacs.git#main
   #+end_src
*** Run
   Examples below assume Docker image was built and tagged as ~kelleyk-emacs~ as shown above.

   After building, you can run a one-off container which will be later deleted (due to the ~docker~ command ~--rm~ switch), just to print the Emacs version by passing the ~--version~ switch:
   #+begin_src shell
   docker run --rm -it kelleyk-emacs --version
   #+end_src
   Mount your home's ~.emacs.d~ directory, but read-only:
   #+begin_src shell
   docker run --rm -it -v $HOME/.emacs.d/:/root/.emacs.d/:ro kelleyk-emacs
   #+end_src
   The above examples will run TTY Emacs due to no X11 running inside the container. For running GUI Emacs use [[https://github.com/mviereck/x11docker][x11docker]], which will handle required X11 sharing to Docker container. Check x11docker docs for more info.
